channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cmake>=3.11
  - cudatoolkit=9.0
  - python=3.6.8
  - pytorch=1.0.1
  - torchvision=0.2.2
  - numba=0.43.1
  - numpy=1.16.2
  - scipy=1.2.1
  - pip=19.0.3
  - quaternion>=2019.3.01
  - tensorflow=1.13
  - pip:
    - opencv-python>=3.0.0
    - tqdm>=4.31.0
    - gym==0.10.9
    - imageio>=2.5.0
    - imageio-ffmpeg>=0.2.0
    - matplotlib>=3.0.3
    - attrs
    - yacs
    - Pillow>=6.0.0
    - "git+https://github.com/openai/baselines.git@5d8041d18e04a83fc0ebb29fdb7e208224868e1b"
    - "git+https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail.git@b4133ecb9528d965cae4f1d4618bd5eff03de126"
    - "git+https://github.com/danielgordon10/dg_util.git@26252345881ffdf9b47b48d042129708c748bcf7"

